import dotenv from "dotenv";

dotenv.config();

export const config = {
  PORT: process.env.PORT,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  MONGODB_URL: process.env.MONGODB_URL,
  CONFIG_SECRET_KEY: process.env.CONFIG_SECRET_KEY,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  SESSION_SECRET: process.env.SESSION_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
  FRONTEND_URL: process.env.FRONTEND_URL,
  RETELL_API_KEY: process.env.RETELL_API_KEY,
  NAME: process.env.NAME,
  BACKFILL_CALL_DETAILS_TIME_GAP_IN_SEC: process.env.BACKFILL_CALL_DETAILS_TIME_GAP_IN_SEC,
  BACKFILL_CAMPAIGN_EXEC_HISTORY_TIME_GAP_IN_SEC:
    process.env.BACKFILL_CAMPAIGN_EXEC_HISTORY_TIME_GAP_IN_SEC,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
};
